### ISSUE TITLE
.NET 8 Headless issues

### ISSUE THREAD

**Issue by troyBORG** [resonite-modding-group/ResoniteModLoader#14]
```
at Mono.Cecil.ExportedType.Resolve()
   at Mono.Cecil.MetadataResolver.GetType(Mono.Cecil.ModuleDefinition, Mono.Cecil.TypeReference)
   at Mono.Cecil.MetadataResolver.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ModuleDefinition.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ExportedType.Resolve()
   at Mono.Cecil.MetadataResolver.GetType(Mono.Cecil.ModuleDefinition, Mono.Cecil.TypeReference)
   at Mono.Cecil.MetadataResolver.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ModuleDefinition.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ExportedType.Resolve()
   at Mono.Cecil.MetadataResolver.GetType(Mono.Cecil.ModuleDefinition, Mono.Cecil.TypeReference)
   at Mono.Cecil.MetadataResolver.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ModuleDefinition.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ExportedType.Resolve()
   at Mono.Cecil.MetadataResolver.GetType(Mono.Cecil.ModuleDefinition, Mono.Cecil.TypeReference)
   at Mono.Cecil.MetadataResolver.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.ModuleDefinition.Resolve(Mono.Cecil.TypeReference)
   at Mono.Cecil.TypeReference.Resolve()
   at FrooxEngine.Weaver.AssemblyPostProcessor.Process(System.String, System.String ByRef, System.String)
   at FrooxEngine.Weaver.AssemblyPostProcessor.Process(System.String, System.String)
   at FrooxEngine.Engine+<ProcessStartupCommands>d__322.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FrooxEngine.Engine+<ProcessStartupCommands>d__322, FrooxEngine, Version=2024.7.12.12, Culture=neutral, PublicKeyToken=null]](<ProcessStartupCommands>d__322 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[FrooxEngine.Engine+<ProcessStartupCommands>d__322, FrooxEngine, Version=2024.7.12.12, Culture=neutral, PublicKeyToken=null]](<ProcessStartupCommands>d__322 ByRef)
   at FrooxEngine.Engine.ProcessStartupCommands(FrooxEngine.LaunchOptions)
   at FrooxEngine.Engine+<Initialize>d__319.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FrooxEngine.Engine+<Initialize>d__319, FrooxEngine, Version=2024.7.12.12, Culture=neutral, PublicKeyToken=null]](<Initialize>d__319 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[FrooxEngine.Engine+<Initialize>d__319, FrooxEngine, Version=2024.7.12.12, Culture=neutral, PublicKeyToken=null]](<Initialize>d__319 ByRef)
   at FrooxEngine.Engine.Initialize(System.String, FrooxEngine.LaunchOptions, FrooxEngine.ISystemInfo, FrooxEngine.IInternalResource, FrooxEngine.IEngineInitProgress)
   at FrooxEngine.StandaloneFrooxEngineRunner+<Initialize>d__36.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FrooxEngine.StandaloneFrooxEngineRunner+<Initialize>d__36, FrooxEngine, Version=2024.7.12.12, Culture=neutral, PublicKeyToken=null]](<Initialize>d__36 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[FrooxEngine.StandaloneFrooxEngineRunner+<Initialize>d__36, FrooxEngine, Version=2024.7.12.12, Culture=neutral, PublicKeyToken=null]](<Initialize>d__36 ByRef)
   at FrooxEngine.StandaloneFrooxEngineRunner.Initialize(FrooxEngine.LaunchOptions)
   at FrooxEngine.Headless.Program+<Main>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[FrooxEngine.Headless.Program+<Main>d__15, Resonite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__15 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[FrooxEngine.Headless.Program+<Main>d__15, Resonite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__15 ByRef)
   at FrooxEngine.Headless.Program.Main(System.String[])
   at FrooxEngine.Headless.Program.<Main>(System.String[])
./StartHeadless.sh: line 15:   550 Aborted                 dotnet ~/Steam/steamapps/common/Resonite/Headless/net8.0/Resonite.dll -LoadAssembly "Libraries/ResoniteModLoader.dll" -c /Config/Config.json -l /Logs
```

I've updated, the files already to the new 3.0 version of the mods

**Comment by XDelta** [comment]
Can you provide a full log or more of it?

**Comment by troyBORG** [comment]
umm...  give me a moment.  I rolled back the headless container before I changed anything in my config.  As I changed it from using that .net mod to using the offical test...

**Comment by troyBORG** [comment]
[ResoniteServer-2024.7.12.12-2024-07-12-05_31_01.log](https://github.com/user-attachments/files/16189632/ResoniteServer-2024.7.12.12-2024-07-12-05_31_01.log)

**Comment by troyBORG** [comment]
[Mod.log](https://github.com/user-attachments/files/16189936/Mod.log)
[noMods.log](https://github.com/user-attachments/files/16189937/noMods.log)

Ok here is two logs.  One when I try having it load Mods.  And one without loading mods

**Comment by troyBORG** [comment]
[03_20_26.log](https://github.com/user-attachments/files/16190856/03_20_26.log)

Well it seems to be booting now.  But I don't think it loaded any mods, but I got it to boot when I think its loading the modloader.

**Comment by troyBORG** [comment]
[12_44_24.log](https://github.com/user-attachments/files/16197721/12_44_24.log)

OK so 2024.7.12.933 update fixed the issue with not logging in.  But it now isn't loading the ModLoader...

I'm launching it with..

```dotnet ~/Steam/steamapps/common/Resonite/Headless/net8.0/Resonite.dll -LoadAssembly "/Libraries/ResoniteModLoader.dll" -c /Config/Config.json -l /Logs```

**Comment by XDelta** [comment]
Looks to be just needing the .Net 8 build of harmony. I've added `0Harmony-Net8.dll` to the latest release.
